name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: List repository contents
        run: ls -al

      - name: Deploy to FTP server
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "Connecting to FTP server: $FTP_SERVER"
          lftp -c "set ftp:ssl-allow no; \
                   open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; \
                   ls; \
                   mkdir -p html/testing || true; \
                   mirror -R ./testing"