name: Deploy to Mittwald via SSH

on:
  push:
    branches:
      - main  # Change this to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Mittwald
      run: |
        ssh -o StrictHostKeyChecking=no p625131@p625131.webspaceconfig.de << 'EOF'
          cd /html/wordpress
          ls -la  # List files in the WordPress directory
          # Add any additional deployment commands here
          # e.g., git pull, build commands, etc.
        EOF
