name: FTP Deploy

on: 
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install lftp
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp

    - name: Verify lftp installation
      run: lftp --version

    - name: Deploy to FTP server
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        echo "Connecting to FTP server: $FTP_SERVER"
        lftp -c "set ftp:ssl-allow no; \
                 open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; \
                 mkdir -p html/testing; \
                 mirror -R ./html/testing"
